### PR TITLE
Allow newer dependencies

### LINKED ISSUE #4: Doesn't allow warp-3.4
This new release series called warp-3.4 is not allowed by the bounds in the cabal file of wai-handler-launch.

See:

* https://github.com/commercialhaskell/stackage/issues/7287

### PR DESCRIPTION
**Pull request by ysangkok**
Fixes #4

### CODE REVIEW

**Comment by ysangkok** [comment]
@snoyberg , would it be possible to merge this?

**Comment by snoyberg** [comment]
I'm really overall looking for others to pick up maintenance of packages they're looking at, I'm not looking at maintaining version bounds here going forward. If you're interested, I'd be happy to give you maintainership here and on Hackage.

**Comment by ysangkok** [comment]
Yeah, sure, I'd be happy to take over maintainership.  My hackage user is http://hackage.haskell.org/user/janus . Maybe @simonmichael would be interested too, since he actually uses the package.

**Comment by snoyberg** [comment]
@simonmichael is always welcome to be a maintainer on any of my repos :)

I've invited both of you on GitHub, and @ysangkok you now have maintainer access on Hackage for the three packages in this PR.

**Comment by ysangkok** [comment]
Thanks, much appreciated!

**Comment by simonmichael** [comment]
Thank you both, and for taking it over @ysangkok. Yes, I am using [wai-handler-launch](https://hackage.haskell.org/package/wai-handler-launch) for hledger-web.

**Pull request merged**
